### ISSUE TITLE
Build errors with g++:  domain_error,memcpy,memcmp used without being declared

### ISSUE THREAD

**Issue by mbodart** [WebAssembly/wasmint#7]
I encountered a few compilation errors when building with g++ 4.8.3,
which are easily fixed with an include of <stdexcept> in HeapPatch.h
and an include of <cstring> in ByteInputStream.cpp and Variable.cpp.

1) When compiling libwasmint/interpreter/heap/Heap.cpp, HeapPatch.h references
   std::domain_error.

libwasmint/interpreter/heap/HeapPatch.h:57:27: error: ?domain_error? is not a member of ?std?
                     throw std::domain_error("Can't apply a HeapPatch that grows memory");

2) In libwasmint/serialization/ByteInputStream.cpp, memcpy is used
   without being declared.

libwasmint/serialization/ByteInputStream.cpp:54:46: error: ?memcpy? was not declared in this scope
     memcpy(result.value(), data, type->size());

3) Several uses of memcpy and memcmp without a declaration in
   wasm-module/src/Variable.cpp.

wasm-module/src/Variable.cpp:38:54: error: ?memcpy? was not declared in this scope
         memcpy(value_, newData.data(), newData.size());

wasm-module/src/Variable.cpp:118:52: error: ?memcpy? was not declared in this scope
         memcpy(result.data(), value_, type_->size());

wasm-module/src/Variable.cpp:152:58: error: ?memcmp? was not declared in this scope
         if (memcmp(value_, variable.value_, type().size()) != 0)

**Comment by mbodart** [comment]
It looks like the markdown stripped my bracketed include file names.
The necessary include files are stdexcept (for std::domain_error) and cstring (for memcpy/memcmp).

**Comment by Teemperor** [comment]
This was fixed in commit dd7fe5e0c8ed8b4d6d077dd3e19cfc87d67c0e71 + 7 parents.
Those commits also replaced everything that relied on the <regex> header as gcc 4.8 only provides a stub implementation for it.
